[project]
name = "calculator_mcp"
version = "0.1.0"
requires-python = ">=3.10"
dependencies = ["mcp"]

[project.scripts]
calculator_mcp = "calculator_mcp:master"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"