[project]
name = "mcp-calculator"
version = "0.1.0"
requires-python = ">=3.10"
dependencies = ["mcp"]

[project.scripts]
mcp-calculator = "mcp-calculator:master"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"